export const FETCH_VIRUS_DATA = 'FETCH_VIRUS_DATA';
export const FETCH_DATES = 'FETCH_DATES';
export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_TOTAL_CASES = 'FETCH_TOTAL_CASES';
export const FETCH_POINTS = 'FETCH_POINTS';
export const FETCH_CLUSTER_POINTS = 'FETCH_CLUSTER_POINTS';
